---
- name: Setup enterprise service and monitoring
  hosts: web_servers
  become: true  
  vars_files:
    - ./config.yml 

  tasks:
    - name: Ensure package manager cache is up-to-date
      ansible.builtin.package:
        update_cache: yes

    - name: Install Apache web server (httpd)
      ansible.builtin.package:
        name: httpd
        state: present

    - name: Start and enable Apache service
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: yes

    - name: Download Node Exporter binary
      ansible.builtin.get_url:
        url: "https://github.com/prometheus/node_exporter/releases/download/v1.8.1/node_exporter-1.8.1.linux-amd64.tar.gz"
        dest: /tmp/node_exporter.tar.gz
        mode: '0644'
      when: monitoring_tool is defined and monitoring_tool == "node_exporter"

    - name: Extract Node Exporter
      ansible.builtin.unarchive:
        src: /tmp/node_exporter.tar.gz
        dest: /usr/local/bin/
        remote_src: yes
        extra_opts: [--strip-components=1]
      when: monitoring_tool is defined and monitoring_tool == "node_exporter"

    - name: Create systemd service for Node Exporter
      ansible.builtin.copy:
        dest: /etc/systemd/system/node_exporter.service
        content: |
          [Unit]
          Description=Prometheus Node Exporter
          After=network.target

          [Service]
          ExecStart=/usr/local/bin/node_exporter
          User=nobody
          Group=nogroup

          [Install]
          WantedBy=multi-user.target
      when: monitoring_tool is defined and monitoring_tool == "node_exporter"

    - name: Start and enable Node Exporter
      ansible.builtin.systemd:
        name: node_exporter
        state: started
        enabled: yes
      when: monitoring_tool is defined and monitoring_tool == "node_exporter"

    - name: Update MOTD
      ansible.builtin.copy:
        dest: /etc/motd
        content: "Ansible Managed by {{ motd_user | default('unknown_user') }}\n"
        owner: root
        group: root
        mode: '0644'

    - name: Clean up Node Exporter tar file
      ansible.builtin.file:
        path: /tmp/node_exporter.tar.gz
        state: absent
      when: monitoring_tool is defined and monitoring_tool == "node_exporter"